networks:
  ledger:
    name: ledger

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3326:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    networks:
      - ledger

  postgres:
    container_name: postgres
    image: 'postgres:17-alpine'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ledger']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
      PGDATA: /data/postgres
    networks:
      - ledger

  ledger:
    image: 'ghcr.io/formancehq/ledger:latest'
    healthcheck:
      test: ['CMD', 'wget', 'http://127.0.0.1:3068/_info', '-O', '-', '-q']
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:3068
    environment:
      POSTGRES_URI: 'postgresql://ledger:ledger@postgres/ledger?sslmode=disable'
    volumes:
      - ./volumes/postgres:/data/postgres
    networks:
      - ledger
