version: "3"

vars:
  GREETING: Hello, World!

tasks:
  config-mysql:
    desc: Up Mysql
    cmds:
      - MYSQL_PWD=mysqlroot mysql --host 127.0.0.1 --port 3326 --user root < ./lib/schema.sql

  default:
    cmds:
      - task --list-all
      -
  setup:
    desc: "Set up the ledger environment with Docker Compose"
    cmds:
      - docker-compose up -d
    silent: false

    clean:
      desc: "Clean up the Docker environment"
      cmds:
        - docker-compose down
      silent: false

  formance:test:
    desc: "Run test and keep containers runing"
    deps:
      - setup
    cmds:
      - task setup
      - npm run build
      - node ./dist/transactionFormanceGenerator.js 
        done
  silent: true
