version: "3"

vars:
  GREETING: Hello, World!

tasks:
  config-mysql:
    desc: Config Mysql
    cmds:
      - MYSQL_PWD=mysqlroot mysql --host 127.0.0.1 --port 3326 --user root < ./lib/schema.sql

  mysql:reset:
    desc: Reset Mysql
    cmds:
      - echo "Dropping the database"
      - MYSQL_PWD=mysqlroot mysql --host 127.0.0.1 --port 3326 --user root -e "DROP DATABASE IF EXISTS ledger;"
      - echo "Creating the database"
      - task config-mysql

  run:
    desc: Run script
    cmds:
      - echo "Starting script"
      - yarn tsc && node ./dist/index.js
  default:
    cmds:
      - task --list-all
      -
  setup:
    desc: "Set up the ledger environment with Docker Compose"
    cmds:
      - docker-compose up -d
    silent: false

    clean:
      desc: "Clean up the Docker environment"
      cmds:
        - docker-compose down
      silent: false

  formance:test:
    desc: "Run test and keep containers runing"
    deps:
      - setup
    cmds:
      - task setup
      - task mysql:reset
      - task formance:reset
      - npm run build
      - node ./dist/transactionFormanceGenerator.js
        done
  silent: true

  formance:reset:
    internal: false
    cmds:
      - echo "Dropping the ledger database"
      - docker cp ledger_bkp.dump postgres:/tmp/mydb_dump.bin &> /dev/null
      - |
        docker exec postgres psql -U ledger -d postgres -c "DROP DATABASE IF EXISTS ledger;" &> /dev/null 
        docker exec postgres psql -U ledger -d postgres -c "CREATE DATABASE ledger;" &> /dev/null
        docker exec postgres pg_restore -U ledger -d ledger -v /tmp/mydb_dump.bin &> /dev/null
    silent: true

  reset:
    desc: Reset Mysql and ledger
    cmds:
      - task mysql:reset
      - task formance:reset
